export const SDG_COLORS: Record<number, { name: string; color: string }> = {
  1: { name: "No Poverty", color: "#E5243B" },
  2: { name: "Zero Hunger", color: "#DDA63A" },
  3: { name: "Good Health and Well-being", color: "#4C9F38" },
  4: { name: "Quality Education", color: "#C5192D" },
  5: { name: "Gender Equality", color: "#FF3A21" },
  6: { name: "Clean Water and Sanitation", color: "#26BDE2" },
  7: { name: "Affordable and Clean Energy", color: "#FCC30B" },
  8: { name: "Decent Work and Economic Growth", color: "#A21942" },
  9: { name: "Industry, Innovation and Infrastructure", color: "#FD6925" },
  10: { name: "Reduced Inequalities", color: "#DD1367" },
  11: { name: "Sustainable Cities and Communities", color: "#FD9D24" },
  12: { name: "Responsible Consumption and Production", color: "#BF8B2E" },
  13: { name: "Climate Action", color: "#3F7E44" },
  14: { name: "Life Below Water", color: "#0A97D9" },
  15: { name: "Life on Land", color: "#56C02B" },
  16: { name: "Peace, Justice and Strong Institutions", color: "#00689D" },
  17: { name: "Partnerships for the Goals", color: "#19486A" },
};
